######################################################################
# Automatically generated by qmake (2.01a) Sun Feb 11 19:41:49 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += window.h
SOURCES += main.cpp window.cpp

QT += widgets
