######################################################################
# Automatically generated by qmake (2.01a) Fri Feb 9 11:12:19 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += window.h
SOURCES += main.cpp window.cpp

QT += widgets
QT += core
