######################################################################
# Automatically generated by qmake (2.01a) Mon Feb 12 06:36:03 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += window.h window2.h window3.h window4.h window5.h
FORMS += window.ui
SOURCES += main.cpp window.cpp window2.cpp window3.cpp window4.cpp window5.cpp
