######################################################################
# Automatically generated by qmake (2.01a) Sat Feb 10 00:10:56 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MainWindow.h
SOURCES += main.cpp MainWindow.cpp

QT += widgets
