######################################################################
# Automatically generated by qmake (2.01a) Sun Feb 11 13:26:23 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += window.h window2.h
SOURCES += main.cpp window.cpp window2.cpp
